language: java
sudo: required
dist: precise
before_install : 
 - sudo apt-get install python-software-properties software-properties-common
 - sudo add-apt-repository ppa:openjdk-r/ppa
 - sudo apt-get update
 - sudo update-ca-certificates -f
 - sudo apt-get install openjdk-8-jdk ant ruby git maven build-essential zlib1g-dev
 - cd /home/travis/build/miteshsavani
 - mkdir installer-build
 - cd installer-build
 - git clone https://github.com/Zimbra/zm-build.git
 - cd zm-build
 - git checkout origin/develop
 - ./build.pl --build-no=1713 --build-ts=`date +'%Y%m%d%H%M%S'` --build-release=JUDASPRIEST --build-release-no=8.7.6 --build-release-candidate=GA --build-type=FOSS --build-thirdparty-server=files.zimbra.com --no-interactive
 - find -follow
 - hostname
 - mkdir ../.zcs-deps
 - cd /home/travis/build/miteshsavani/zm-selenium
 - git clone https://github.com/Zimbra/zm-ajax.git ../zm-ajax
 - git clone https://github.com/Zimbra/zimbra-package-stub.git ../zimbra-package-stub
 - git clone https://github.com/Zimbra/zm-mailbox.git ../zm-mailbox
 - git clone https://github.com/Zimbra/zm-zcs.git ../zm-zcs
 - git clone https://github.com/Zimbra/zm-web-client.git ../zm-web-client
 - git clone https://github.com/Zimbra/zm-zimlets.git ../zm-zimlets
 - cd ../zm-mailbox
 - ant publish-local-all -Dzimbra.buildinfo.version=8.7.6_GA
 - cd ../zm-selenium
cache: 
 directories:
  - /home/travis/.ivy2/cache
script: ant Run-ExecuteHarnessMain
notifications:
  email:
    recipients:
      - mitesh.savani810@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
