language: java

before_install : 
 - mkdir installer-build
 - cd installer-build
 - git clone https://github.com/Zimbra/zm-build.git
 - cd zm-build
 - git checkout origin/develop
 - ./build.pl --build-no=1713 --build-ts=`date +'%Y%m%d%H%M%S'`
 - find -follow
 - hostname
 - mkdir ../.zcs-deps
 - cd /home/travis/build/miteshsavani/zm-selenium
 - git clone https://github.com/Zimbra/zm-ajax.git ../zm-ajax
 - git clone https://github.com/Zimbra/zimbra-package-stub.git ../zimbra-package-stub
 - git clone https://github.com/Zimbra/zm-mailbox.git ../zm-mailbox
 - git clone https://github.com/Zimbra/zm-zcs.git ../zm-zcs
 - git clone https://github.com/Zimbra/zm-web-client.git ../zm-web-client
 - git clone https://github.com/Zimbra/zm-zimlets.git ../zm-zimlets
 - cd ../zm-mailbox
 - ant publish-local-all -Dzimbra.buildinfo.version=8.7.6_GA
 - cd ../zm-selenium
cache: 
 directories:
  - /home/travis/.ivy2/cache
script: ant Run-ExecuteHarnessMain
notifications:
  email:
    recipients:
      - mitesh.savani810@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
