version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:latest-browsers
     steps:
       - checkout
       - run: echo "hello world"
       - run: mkdir ../.zcs-deps
       - run: echo download zm-ajax from github
       - run: git clone https://github.com/Zimbra/zm-ajax.git ../zm-ajax
       - run:
         command: |
            echo Running test
            mkdir -p /tmp/test-results
