version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:latest-browsers
     steps:
       - checkout
       - run: echo "hello world"
       - run: |
            mkdir ../.zcs-deps
            mkdir ../.ivy2
            cd ../.ivy2
            mkdir cache
            echo download zm-ajax from github
            git clone https://github.com/Zimbra/zm-ajax.git ../zm-ajax
            git clone https://github.com/Zimbra/zimbra-package-stub.git ../zimbra-package-stub
            git clone https://github.com/Zimbra/zm-mailbox.git ../zm-mailbox
            git clone https://github.com/Zimbra/zm-zcs.git ../zm-zcs
            git clone https://github.com/Zimbra/zm-web-client.git ../zm-web-client
            git clone https://github.com/Zimbra/zm-zimlets.git ../zm-zimlets
            cd ../zm-mailbox
            ant publish-local-all -Dzimbra.buildinfo.version=8.7.6_GA
            git clone https://github.com/miteshsavani/zm-selenium.git ../zm-selenium
            cd ../zm-selenium
            ant Run-ExecuteHarnessMain
            
