version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:latest-browsers
     steps:
       - checkout
       - run: echo "hello world"
       - run: mkdir ../.zcs-deps
       - run: 
         command: |
            echo download zm-ajax from github
            git clone https://github.com/Zimbra/zm-ajax.git ../zm-ajax
