version: 2
jobs:
  build:
    working_directory: ~/mitesh-demo
docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
       - checkout
       - run: mkdir ../.zcs-deps
       - run: echo "hello world"
