version: 2
jobs:
   build:
     docker:
       - image: zimbra/zcs-foss
     steps:
       - run: sudo apt-get -y install git; sudo apt-get -y install wget; sudo apt-get -y install ant; sudo apt-get update
       - checkout
       - run: echo "hello world"
       - run: |
            mkdir ../.zcs-deps
            cd ../.zcs-deps
            wget http://www.java2s.com/Code/JarDownload/ant-contrib/ant-contrib-1.0b1.jar.zip
            unzip -a ant-contrib-1.0b1.jar.zip
            mkdir ../.ivy2
            cd ../.ivy2
            mkdir cache
            echo download zm-ajax from github
            git clone https://github.com/Zimbra/zm-ajax.git ../zm-ajax
            git clone https://github.com/Zimbra/zimbra-package-stub.git ../zimbra-package-stub
            git clone https://github.com/Zimbra/zm-mailbox.git ../zm-mailbox
            git clone https://github.com/Zimbra/zm-zcs.git ../zm-zcs
            git clone https://github.com/Zimbra/zm-web-client.git ../zm-web-client
            git clone https://github.com/Zimbra/zm-zimlets.git ../zm-zimlets
            cd ../zm-mailbox
            ant publish-local-all -Dzimbra.buildinfo.version=8.7.6_GA
            cd ~/zm-selenium
            ant Run-ExecuteHarnessMain
            - save_cache:
                 key: v1-myapp-cache
                 paths:
                        - ~/zm-ajax
                        - ~/zm-mailbox
                        - ~/.zcs-deps
            
